# Generated by Django 3.2.9 on 2021-11-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=200)),
                ('imagine', models.ImageField(default='media/user/default.jpeg', upload_to='')),
                ('locatie', models.CharField(max_length=200)),
                ('date', models.TextField()),
                ('email', models.CharField(max_length=200)),
                ('parola', models.CharField(max_length=200)),
            ],
        ),
    ]
