# Generated by Django 3.2.9 on 2021-11-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imagine',
            field=models.ImageField(default='media/user/default.jpeg', upload_to='media/user'),
        ),
    ]
