# Generated by Django 3.2.9 on 2021-11-05 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_user_imagine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='imagine',
        ),
    ]
