# Generated by Django 3.2.9 on 2021-11-05 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_remove_user_imagine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='parola',
            new_name='password',
        ),
    ]
