# Generated by Django 3.2.9 on 2021-11-05 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
